apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: devops-binding
spec:
  type: bindings.azure.servicebusqueues
  version: v1
  metadata:
    - name: connectionString # Required when not using Azure Authentication.
      secretKeyRef:
        name: "LogisticsPartner:Invoice:AzureServiceBus:ConnectionString"
        key: "LogisticsPartner:Invoice:AzureServiceBus:ConnectionString"
    - name: queueName # Required when not using Azure Authentication.
      value: logistics-partner-invoice
auth:
  secretStore: secretstore
