site_name: Hexalith
site_url: https://https://hexalith.readthedocs.io/
nav:
    - Home: 
        - About Hexalith: docs/home/index.md
        - GitHub: README.md
    - Getting Started:
        - Create Hexalith application: docs/getting-started/create-application.md
        - Install preview packages: docs/getting-started/preview-package-source.md
      
theme: readthedocs
# Repository
repo_name: Hexalith/Hexalith
repo_url: https://github.com/Hexalith/Hexalith

