site_name: Hexalith
nav:
    - Home: index.md
    - Getting Started:
        - Create Hexalith application: getting-started/create-application.md
      
theme: readthedocs
repo_name: Hexalith/Hexalith
repo_url: https://github.com/Hexalith/Hexalith/