apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore
spec:
  type: secretstores.local.file
  version: v1
  metadata:
    - name: secretsFile
      value: "C:/Dev/Christofle/LogisticsPartner/Hexalith/src/Servers/Hexalith.Server.Sales/secrets.json"
    - name: nestedSeparator
      value: ":"
