namespace Hexalith.Application.Commands
{
    using System.Threading.Tasks;

    using Hexalith.Application.Commands;

    /// <summary>
    /// Interface ICommandLogger
    /// </summary>
    /// <autogeneratedoc/>
    public interface ICommandLogger
    {
        /// <summary>
        /// Logs the specified command.
        /// </summary>
        /// <param name="command">The command.</param>
        /// <returns>Task.</returns>
        /// <autogeneratedoc/>
        Task Log(object command);
    }
}