// ***********************************************************************
// Assembly         : Hexalith.Infrastructure.MicrosoftSemanticKernel
// Author           : Jérôme Piquot
// Created          : 05-30-2023
//
// Last Modified By : Jérôme Piquot
// Last Modified On : 05-30-2023
// ***********************************************************************
// <copyright file="SemanticKernelController.cs" company="Fiveforty SAS Paris France">
//     Copyright (c) Fiveforty SAS Paris France. All rights reserved.
//     Licensed under the MIT license.
//     See LICENSE file in the project root for full license information.
// </copyright>
// <summary></summary>
// ***********************************************************************

namespace Hexalith.Infrastructure.TeamsBot.Controllers;

using System.Collections.Generic;

// Copyright (c) Microsoft. All rights reserved.
using System.Linq;
using System.Threading.Tasks;

using Hexalith.Application.ArtificialIntelligence;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.SemanticKernel;
using Microsoft.SemanticKernel.AI;
using Microsoft.SemanticKernel.Orchestration;
using Microsoft.SemanticKernel.SkillDefinition;

/// <summary>
/// Class SemanticKernelController.
/// Implements the <see cref="ControllerBase" />.
/// </summary>
/// <seealso cref="ControllerBase" />
[ApiController]
public class SemanticKernelController : ControllerBase
{
    /// <summary>
    /// The logger.
    /// </summary>
    private readonly ILogger<SemanticKernelController> _logger;

    /// <summary>
    /// Initializes a new instance of the <see cref="SemanticKernelController"/> class.
    /// </summary>
    /// <param name="logger">The logger.</param>
    public SemanticKernelController(ILogger<SemanticKernelController> logger) => _logger = logger;

    /// <summary>
    /// Invoke a Semantic Kernel function on the server.
    /// </summary>
    /// <param name="kernel">Semantic kernel obtained through dependency injection.</param>
    /// <param name="ask">Prompt along with its parameters.</param>
    /// <param name="skillName">Skill in which function to invoke resides.</param>
    /// <param name="functionName">Name of function to invoke.</param>
    /// <returns>Results consisting of text generated by invoked function along with the variable in the Semantic Kernel that generated it.</returns>
    /// <remarks>We create and use a new kernel for each request.
    /// We feed the kernel the ask received via POST from the client
    /// and attempt to invoke the function with the given name.</remarks>
    [Authorize]
    [Route("skills/{skillName}/functions/{functionName}/invoke")]
    [HttpPost]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<ActionResult<Answer>> InvokeFunctionAsync(
        [FromServices] IKernel kernel,
        [FromBody] Ask ask,
        string skillName,
        string functionName)
    {
        _logger.LogDebug("Received call to invoke {SkillName}/{FunctionName}", skillName, functionName);

        if (string.IsNullOrWhiteSpace(ask.Input))
        {
            return BadRequest("Input is required.");
        }

        // Put ask's variables in the context we will use.
        ContextVariables contextVariables = new(ask.Input);
        foreach (KeyValuePair<string, string> input in ask.Variables)
        {
            contextVariables.Set(input.Key, input.Value);
        }

        // Get the function to invoke
        ISKFunction? function = null;
        try
        {
            function = kernel.Skills.GetFunction(skillName, functionName);
        }
        catch (KernelException)
        {
            return NotFound($"Failed to find {skillName}/{functionName} on server");
        }

        // Run the function.
        SKContext result = await kernel.RunAsync(contextVariables, function!);
        return result.ErrorOccurred
            ? result.LastException is AIException aiException && aiException.Detail is not null
                ? (ActionResult<Answer>)BadRequest(string.Concat(aiException.Message, " - Detail: " + aiException.Detail))
                : (ActionResult<Answer>)BadRequest(result.LastErrorDescription)
            : (global::Microsoft.AspNetCore.Mvc.ActionResult<global::Hexalith.Application.ArtificialIntelligence.Answer>)Ok(new Answer { Value = result.Result, Variables = result.Variables.Select(v => new KeyValuePair<string, string>(v.Key, v.Value)) });
    }
}