namespace Hexalith.WorkItems.Infrastructure.DevOps
{
    using System;
    using System.Runtime.Serialization;

    /// <summary>
    /// Class InvalidWorkItemUrlException. Implements the <see cref="System.Exception"/>.
    /// </summary>
    /// <seealso cref="System.Exception"/>
    /// <autogeneratedoc/>
    [Serializable]
    internal class InvalidWorkItemUrlException : Exception
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InvalidWorkItemUrlException"/> class.
        /// </summary>
        /// <autogeneratedoc/>
        public InvalidWorkItemUrlException()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InvalidWorkItemUrlException"/> class.
        /// </summary>
        /// <param name="url">The URL.</param>
        /// <autogeneratedoc/>
        public InvalidWorkItemUrlException(string url)
            : base($"Invalid work item url : {url}")
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InvalidWorkItemUrlException"/> class.
        /// </summary>
        /// <param name="url">The URL.</param>
        /// <param name="innerException">The inner exception.</param>
        /// <autogeneratedoc/>
        public InvalidWorkItemUrlException(string url, Exception? innerException)
            : base($"Invalid work item url : {url}", innerException)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InvalidWorkItemUrlException"/> class.
        /// </summary>
        /// <param name="info">
        /// The <see cref="SerializationInfo"/> that holds the
        /// serialized object data about the exception being thrown.
        /// </param>
        /// <param name="context">
        /// The <see cref="StreamingContext"/> that contains
        /// contextual information about the source or destination.
        /// </param>
        /// <autogeneratedoc/>
        protected InvalidWorkItemUrlException(SerializationInfo info, StreamingContext context)
            : base(info, context)
        {
        }
    }
}