namespace Hexalith.WorkItems.Infrastructure.DevOps
{
    /// <summary>
    /// Class LinkTypes.
    /// </summary>
    /// <autogeneratedoc/>
    internal static class LinkTypes
    {
        /// <summary>
        /// The child link type.
        /// </summary>
        public const string Child = "System.LinkTypes.Hierarchy-Forward";

        /// <summary>
        /// The parent link type.
        /// </summary>
        public const string Parent = "System.LinkTypes.Hierarchy-Reverse";
    }
}