namespace Hexalith.WorkItems.Infrastructure.DevOps
{
    /// <summary>
    /// Class WorkItemType.
    /// </summary>
    /// <autogeneratedoc/>
    internal static class WorkItemType
    {
        /// <summary>
        /// The bug work item type.
        /// </summary>
        public const string Bug = "Bug";

        /// <summary>
        /// The epic work item type.
        /// </summary>
        public const string Epic = "Epic";

        /// <summary>
        /// The Feature work item type.
        /// </summary>
        public const string Feature = "Feature";

        /// <summary>
        /// The task work item type.
        /// </summary>
        public const string Task = "Task";

        /// <summary>
        /// The user story work item type.
        /// </summary>
        public const string UserStory = "User Story";
    }
}