apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: d365fno_customers_binding
spec:
  type: bindings.azure.servicebusqueues
  version: v1
  metadata:
    - name: connectionString # Required when not using Azure Authentication.
      secretKeyRef:
        name: "Dynamics365Finance:Customer:AzureServiceBus:ConnectionString"
        key: "Dynamics365Finance:Customer:AzureServiceBus:ConnectionString"
    - name: queueName # Required when not using Azure Authentication.
      value: d365fno-customers
auth:
  secretStore: secretstore
