namespace Hexalith.Infrastructure.InMemory.Queries
{
    using System;
    using System.Collections.Generic;
    using System.Collections.Immutable;
    using System.Threading;
    using System.Threading.Tasks;

    using Hexalith.Application.Exceptions;
    using Hexalith.Application.Messages;
    using Hexalith.Application.Queries;

    /// <summary>
    /// Implements the <see cref="IQueryBus" />.
    /// </summary>
    /// <seealso cref="IQueryBus" />
    /// <autogeneratedoc />
    public class InMemoryQueryBus : IQueryBus
    {
        private readonly ImmutableDictionary<Type, Func<IQueryHandler>> _handlers;

        public InMemoryQueryBus(Dictionary<Type, Func<IQueryHandler>> handlers)
        {
            _handlers = handlers?.ToImmutableDictionary() ?? throw new ArgumentNullException(nameof(handlers));
        }

        public Task<TResult> Dispatch<TQuery, TResult>(Envelope<TQuery> envelope, CancellationToken cancellationToken = default)
            where TQuery : class
        {
            if (!_handlers.TryGetValue(envelope.Message.GetType(), out Func<IQueryHandler>? handlerFunc))
            {
                return Task.FromException<TResult>(new QueryHandlerNotFoundException(envelope.Message.GetType()));
            }
            IQueryHandler<TQuery, TResult>? handler = handlerFunc() as IQueryHandler<TQuery, TResult>;
            return handler?.Handle(envelope, cancellationToken)
                ?? Task.FromException<TResult>(new InvalidQueryHandlerTypeException(handlerFunc().GetType(), typeof(IQueryHandler<TQuery, TResult>)));
        }

        public Task<object?> Dispatch(IEnvelope envelope, CancellationToken cancellationToken = default)
        {
            if (!_handlers.TryGetValue(envelope.Message.GetType(), out Func<IQueryHandler>? handlerFunc))
            {
                return Task.FromException<object?>(new QueryHandlerNotFoundException(envelope.GetType()));
            }
            IQueryHandler? handler = handlerFunc();
            return handler?.Handle(envelope, cancellationToken)
                ?? Task.FromException<object?>(new InvalidQueryHandlerTypeException(handlerFunc().GetType(), typeof(IQueryHandler)));
        }
    }
}