namespace Hexalith.Application.Events
{
    /// <summary>
    /// Interface IEventHandlerProvider
    /// </summary>
    /// <autogeneratedoc/>
    public interface IEventHandlerProvider
    {
        /// <summary>
        /// Gets the handler.
        /// </summary>
        /// <param name="eventToHandle">The event to handle.</param>
        /// <returns>IEventHandler.</returns>
        /// <autogeneratedoc/>
        IEventHandler GetHandler(object eventToHandle);
    }
}