name: Preview - CI
on:
  push:
    paths-ignore:
      - '**/*.md'
      - 'mkdocs.yml'
      - 'docs/**/*'
    branches: [ main ]
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: Build, Test, Deploy
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive
    - name: Setup .NET 7.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Build Version
      run: |
        dotnet tool install --global minver-cli --version 4.2.0
        version=$(minver --tag-prefix v -v e -d preview)
        echo "MINVERVERSIONOVERRIDE=$version" >> $GITHUB_ENV
        echo "VERSION=$version" >> $GITHUB_ENV        
    - name: Build
      run: |
        dotnet build --configuration Release
    - name: Unit Tests
      run: |
        dotnet test -c Release --no-restore --no-build ./test/Hexalith.Tests/Hexalith.Tests.csproj 
    - name: Deploy preview nuget packages
      if: matrix.os == 'ubuntu-latest'
      run: |
        dotnet pack -c Release --no-restore --no-build
        dotnet nuget push './src/**/*.nupkg' -k ${{secrets.GITHUB_TOKEN}} -n -s https://nuget.pkg.github.com/Hexalith/index.json --skip-duplicate