name: Preview - CI
on:
  push:
    paths-ignore:
      - '**/*.md'
      - 'mkdocs.yml'
      - 'docs/**/*'
    branches: [ main ]
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
jobs:
  publish:
    runs-on: ubuntu-latest
    name: Build, Test, Publish
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Build Version
      run: |
        dotnet tool install --global minver-cli --version 4.3.0
        version=$(minver -t v -v e -d preview)
        echo "MINVERVERSIONOVERRIDE=$version" >> $GITHUB_ENV
        echo "VERSION=$version" >> $GITHUB_ENV
        echo "VERSION=$version"
    - name: Build
      run: |
        dotnet build --configuration Release -p:Version=${{ env.VERSION }}
    - name: Unit Tests
      run: |
        dotnet test -c Release --no-restore --no-build ./test/Hexalith.UnitTests/Hexalith.UnitTests.csproj 
    - name: Deploy preview nuget packages
      run: |
        dotnet nuget push './src/Core/**/*.nupkg' -k ${{secrets.GITHUB_TOKEN}} -n -s https://nuget.pkg.github.com/Hexalith/index.json --skip-duplicate
    - name: Login to container registry ${{ vars.AZURE_REGISTRY }}
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.AZURE_REGISTRY }}
        username: ${{ secrets.AZURE_APPLICATIONID }}
        password: ${{ secrets.AZURE_APPLICATIONSECRET }}
    - name: Publish and push the servers container images to the container registry
      run: |
          dotnet publish './src/Server/**/*.csproj' --configuration Release --os linux --arch x64 /p:PublishProfile=DefaultContainer